version: "3.8"
services:
  http_server:
    image: damlys/ts-project-skeleton:${VERSION:-0.0.12}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN
    environment:
      HTTP_TESTS_ENDPOINT: http://127.0.0.1:8080
    command:
      - run-http-server
