version: "3.8"
services:
  ts-project-skeleton:
    user: "0" #root
    environment:
      NPM_TOKEN: "${NPM_TOKEN}"
      NODE_ENV: development
    entrypoint:
      - npm
    command:
      - run
      - src:repl
    ports:
      - mode: host
        target: 8080
        published: 38080
        protocol: tcp
      - mode: host
        target: 9229
        published: 39229
        protocol: tcp
    volumes:
      - type: volume
        source: npm_cache
        target: /root/.npm
      - type: bind
        source: .
        target: /app

volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
