name: Continuous Delivery
on:
  push:
    branches:
      - master
      - develop
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
jobs:
  job0:
    runs-on: ubuntu-20.04
    env:
      NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
      NODE_ENV: development
    steps:
      - name: Login to Docker Hub
        run: docker login --username="damlys" --password="${{ secrets.DOCKER_TOKEN }}"
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run NPM vulnerability scanning
        run: npm audit --audit-level=high
      - name: Install dependencies
        run: npm install
      - if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        name: Bump version (pre-release)
        run: npm version prerelease --message "Pre-release %s" --ignore-scripts
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Bump version (release)
        run: npm version patch --message "Release %s"

      - name: Build application
        run: npm run build
      - name: Run code format check
        run: npm run format:check
      - name: Run code lint check
        run: npm run lint:check
      - name: Run code tests
        run: npm run test:unit

      - name: Build image
        run: npm run docker:build
      - name: Run Docker vulnerability scanning
        run: npm run docker:audit
        continue-on-error: true
      - name: Copy docker-compose.override.yml
        run: cp ./.github/docker-compose.override.yml ./docker-compose.override.yml
      - name: Run containers
        run: npm run docker:up
      - name: Wait 10s
        run: sleep 10
      - name: Run system tests
        env:
          TESTS_ENDPOINT: http://127.0.0.1:8080
        run: npm run test:e2e
      - name: Destroy containers
        run: npm run docker:down

      - if: github.event_name == 'push'
        name: Publish package
        run: npm publish
      - if: github.event_name == 'push'
        name: Publish image
        run: npm run docker:publish
      - if: github.event_name == 'push'
        name: Publish version
        run: git push && git push --tags
